name: 'test-every-push'

# workflow를 동작하게하는 trigger
# repository에 push 이벤트가 발생할 때마다 실행
on: push

# job은 사용자가 정한 플랫폼을 통해 step이라는 일련의 과정을 실행
jobs:
  test:
    # job의 이름
    name: Test lint, tsc, build
    # 해당 job을 리눅스 환경에서 사용
    runs-on: ubuntu-latest
    
    steps:
      # GitHub Actions는 해당 프로젝트를 리눅스 환경에 checkout하고 나서 실행
      # 마치 우리가 브랜치를 만들 때 checkout하는 것처럼 꼭 필요한 작업.
      # 만들어놓은 Action을 사용할 때는 uses라는 키워드를 사용해야 함.
      - uses: actions/checkout@v2

      # 해당 환경을 Node.js 위에서 실행하겠다고 명시.
      - name: Use Node.js
        uses: actions/setup-node@v2
        # with라는 키워드로 Action에 값을 전달할 수 있다.
        with:
          node-version: ${{ secrets.NODE_VERSION }}
